import { Router } from "express";
import { register, login, logout, refreshToken, forgotPassword, resetPassword, verifyEmail } from "../controllers/auth.controller.js";
import { protect } from "../middlewares/auth.middleware.js";
const router = Router();
router.post("/register",       register);
router.post("/login",          login);
router.post("/logout",         protect, logout);
router.post("/refresh-token",  refreshToken);
router.post("/forgot-password",forgotPassword);
router.put("/reset-password/:token", resetPassword);
router.get("/verify-email/:token",   verifyEmail);
export default router;
