// seed-extra.js — 40 more Indian listings (all states covered)
// Command: node src/seed-extra.js

import dotenv from "dotenv";
dotenv.config();

import mongoose from "mongoose";
import User from "./models/User.model.js";
import Listing from "./models/Listing.model.js";

const EXTRA_LISTINGS = [
  // RAJASTHAN
  {
    title: "Royal Haveli Suite, Jaipur",
    description: "Experience the grandeur of Rajasthan in this beautifully restored 18th-century haveli in the Pink City. Ornate frescoes, arched corridors, and a rooftop terrace with panoramic views of the city make this a truly royal experience. Enjoy authentic Rajasthani thali breakfast included.",
    propertyType: "hotel",
    pricePerNight: 6500,
    cleaningFee: 1000,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Air conditioning", "Breakfast", "Pool", "TV", "Free parking"],
    location: { city: "Jaipur", state: "Rajasthan", country: "India", address: "Hawa Mahal Road, Pink City", coordinates: { lat: 26.9124, lng: 75.7873 } },
    images: [
      { url: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200&h=800&fit=crop", public_id: "seed2/jaipur_haveli_1" },
      { url: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&h=800&fit=crop", public_id: "seed2/jaipur_haveli_2" },
    ],
    avgRating: 4.89, reviewCount: 203,
  },
  {
    title: "Desert Dunes Luxury Camp, Jodhpur",
    description: "Stay in premium Shikar tents with attached bathrooms overlooking the magnificent Mehrangarh Fort. Experience the magic of the Blue City from a unique vantage point. Sunset camel safari, cultural performances, and traditional Marwari dinner included.",
    propertyType: "hotel",
    pricePerNight: 8900,
    cleaningFee: 1200,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Air conditioning", "Breakfast", "BBQ grill", "Free parking", "TV"],
    location: { city: "Jodhpur", state: "Rajasthan", country: "India", address: "Near Mehrangarh Fort", coordinates: { lat: 26.2389, lng: 73.0243 } },
    images: [
      { url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&h=800&fit=crop", public_id: "seed2/jodhpur_camp_1" },
      { url: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200&h=800&fit=crop", public_id: "seed2/jodhpur_camp_2" },
    ],
    avgRating: 4.93, reviewCount: 87,
  },
  // HIMACHAL PRADESH
  {
    title: "Apple Orchard Homestay, Shimla",
    description: "A charming colonial cottage nestled in apple orchards with breathtaking Himalayan views. Wake up to misty mountain mornings, pick fresh apples from the garden, and enjoy homemade jams and local Himachali cuisine. The perfect mountain retreat just 3km from Shimla Mall Road.",
    propertyType: "cottage",
    pricePerNight: 4200,
    cleaningFee: 600,
    maxGuests: 5,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    amenities: ["WiFi", "Heating", "Kitchen", "Breakfast", "Free parking", "Pet friendly"],
    location: { city: "Shimla", state: "Himachal Pradesh", country: "India", address: "Mashobra, Near Shimla", coordinates: { lat: 31.1048, lng: 77.1734 } },
    images: [
      { url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&h=800&fit=crop", public_id: "seed2/shimla_cottage_1" },
      { url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop", public_id: "seed2/shimla_cottage_2" },
    ],
    avgRating: 4.81, reviewCount: 134,
  },
  {
    title: "River Camp Tent, Kasol",
    description: "Premium glamping tents on the banks of the Parvati River in the Kullu Valley. Surrounded by dense pine forests and towering Himalayan peaks. Perfect for trekkers heading to Kheerganga or Pin Parvati Pass. Bonfires every evening with live music.",
    propertyType: "cabin",
    pricePerNight: 2800,
    cleaningFee: 400,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Breakfast", "BBQ grill", "Free parking"],
    location: { city: "Kasol", state: "Himachal Pradesh", country: "India", address: "Parvati River Bank, Kasol", coordinates: { lat: 32.0109, lng: 77.3145 } },
    images: [
      { url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&h=800&fit=crop", public_id: "seed2/kasol_camp_1" },
      { url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&h=800&fit=crop", public_id: "seed2/kasol_camp_2" },
    ],
    avgRating: 4.77, reviewCount: 98,
  },
  // UTTARAKHAND
  {
    title: "Forest Retreat Villa, Rishikesh",
    description: "A stunning riverside villa with yoga deck and private beach access on the holy Ganges. Ideal for wellness retreats, adventure seekers and spiritual travelers. Whitewater rafting, bungee jumping and zip-lining all nearby. Ayurvedic spa treatments available on request.",
    propertyType: "villa",
    pricePerNight: 7500,
    cleaningFee: 1200,
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Pool", "Waterfront", "Breakfast", "Free parking", "Gym"],
    location: { city: "Rishikesh", state: "Uttarakhand", country: "India", address: "Tapovan, Rishikesh", coordinates: { lat: 30.1087, lng: 78.2932 } },
    images: [
      { url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&h=800&fit=crop", public_id: "seed2/rishikesh_villa_1" },
      { url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=1200&h=800&fit=crop", public_id: "seed2/rishikesh_villa_2" },
    ],
    avgRating: 4.95, reviewCount: 167,
  },
  {
    title: "Kumaoni Stone Cottage, Nainital",
    description: "Traditional Kumaoni stone cottage with lake views in the charming hill town of Nainital. Original wooden beamed ceilings, fireplace, and a wrap-around verandah overlooking Naini Lake. Walking distance to the famous Naini Lake boating and the Mall Road.",
    propertyType: "cottage",
    pricePerNight: 3900,
    cleaningFee: 600,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Heating", "Kitchen", "Indoor fireplace", "Free parking", "TV"],
    location: { city: "Nainital", state: "Uttarakhand", country: "India", address: "Near Naini Lake, Nainital", coordinates: { lat: 29.3803, lng: 79.4636 } },
    images: [
      { url: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1200&h=800&fit=crop", public_id: "seed2/nainital_cottage_1" },
      { url: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1200&h=800&fit=crop", public_id: "seed2/nainital_cottage_2" },
    ],
    avgRating: 4.72, reviewCount: 119,
  },
  // KARNATAKA
  {
    title: "Boutique Heritage Hotel, Mysuru",
    description: "An exquisitely restored Indo-Saracenic mansion near the magnificent Mysore Palace. Teak wood interiors, stained glass windows, and antique furnishings transport you to the era of the Wadiyar dynasty. Rooftop restaurant with palace views and traditional Mysore silk shopping nearby.",
    propertyType: "hotel",
    pricePerNight: 5800,
    cleaningFee: 900,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Air conditioning", "Breakfast", "Pool", "TV", "Gym"],
    location: { city: "Mysuru", state: "Karnataka", country: "India", address: "Near Mysore Palace, Mysuru", coordinates: { lat: 12.2958, lng: 76.6394 } },
    images: [
      { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop", public_id: "seed2/mysuru_hotel_1" },
      { url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&h=800&fit=crop", public_id: "seed2/mysuru_hotel_2" },
    ],
    avgRating: 4.86, reviewCount: 241,
  },
  {
    title: "Treehouse Resort, Kabini",
    description: "Wake up to elephant sightings from your private treehouse overlooking the Kabini backwaters and wildlife sanctuary. This unique eco-resort offers jeep safaris, boat rides, and guided nature walks in one of India's finest wildlife corridors. Leopards, tigers, wild dogs and hundreds of bird species await.",
    propertyType: "resort",
    pricePerNight: 14500,
    cleaningFee: 2000,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Air conditioning", "Breakfast", "Waterfront", "Free parking", "TV"],
    location: { city: "Kabini", state: "Karnataka", country: "India", address: "Kabini River Lodge, Nagarhole", coordinates: { lat: 11.9312, lng: 76.3459 } },
    images: [
      { url: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=1200&h=800&fit=crop", public_id: "seed2/kabini_treehouse_1" },
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=800&fit=crop", public_id: "seed2/kabini_treehouse_2" },
    ],
    avgRating: 4.97, reviewCount: 56,
  },
  // TAMIL NADU
  {
    title: "Colonial Bungalow, Ooty",
    description: "A magnificent 1920s British colonial bungalow set in 2 acres of manicured gardens in the Queen of Hill Stations. Original period furniture, roaring fireplace, and sweeping views of the Nilgiri mountains. The famous Ooty Botanical Gardens and toy train station are minutes away.",
    propertyType: "house",
    pricePerNight: 5200,
    cleaningFee: 800,
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    amenities: ["WiFi", "Heating", "Kitchen", "Indoor fireplace", "Free parking", "TV", "Breakfast"],
    location: { city: "Ooty", state: "Tamil Nadu", country: "India", address: "Botanical Garden Road, Ooty", coordinates: { lat: 11.4102, lng: 76.6950 } },
    images: [
      { url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&h=800&fit=crop", public_id: "seed2/ooty_bungalow_1" },
      { url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=1200&h=800&fit=crop", public_id: "seed2/ooty_bungalow_2" },
    ],
    avgRating: 4.83, reviewCount: 178,
  },
  {
    title: "Beach Resort Villa, Mahabalipuram",
    description: "Luxury beachfront villa steps from the UNESCO World Heritage Shore Temple. Watch the sunrise over the Bay of Bengal from your private pool. The villa features contemporary design with local Tanjore art, granite bathrooms, and a private chef on request.",
    propertyType: "villa",
    pricePerNight: 11000,
    cleaningFee: 1800,
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Pool", "Beachfront", "Free parking", "TV", "Breakfast"],
    location: { city: "Mahabalipuram", state: "Tamil Nadu", country: "India", address: "Shore Temple Road, Mahabalipuram", coordinates: { lat: 12.6269, lng: 80.1927 } },
    images: [
      { url: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&h=800&fit=crop", public_id: "seed2/mahabalipuram_villa_1" },
      { url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&h=800&fit=crop", public_id: "seed2/mahabalipuram_villa_2" },
    ],
    avgRating: 4.91, reviewCount: 143,
  },
  // KERALA
  {
    title: "Spice Plantation Villa, Munnar",
    description: "A spectacular villa perched on a working cardamom and tea plantation in the Western Ghats. Sweeping views of tea-carpet hills, cool mountain air, and the intoxicating fragrance of spices. Guided plantation walks, tea tasting sessions, and Kathakali performances arranged.",
    propertyType: "villa",
    pricePerNight: 8200,
    cleaningFee: 1400,
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ["WiFi", "Heating", "Kitchen", "Breakfast", "Free parking", "TV", "Pet friendly"],
    location: { city: "Munnar", state: "Kerala", country: "India", address: "Top Station Road, Munnar", coordinates: { lat: 10.0889, lng: 77.0595 } },
    images: [
      { url: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1200&h=800&fit=crop", public_id: "seed2/munnar_villa_1" },
      { url: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&h=800&fit=crop", public_id: "seed2/munnar_villa_2" },
    ],
    avgRating: 4.94, reviewCount: 221,
  },
  {
    title: "Beachfront Cottage, Varkala",
    description: "Stunning clifftop cottage with uninterrupted Arabian Sea views in Varkala, Kerala's most beautiful beach destination. Ayurvedic massage center on premises, fresh seafood restaurant below, and a beach accessible by private staircase. Ideal for yoga and wellness retreats.",
    propertyType: "cottage",
    pricePerNight: 5600,
    cleaningFee: 800,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Air conditioning", "Beachfront", "Breakfast", "TV"],
    location: { city: "Varkala", state: "Kerala", country: "India", address: "Cliff Road, Varkala Beach", coordinates: { lat: 8.7322, lng: 76.7148 } },
    images: [
      { url: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1200&h=800&fit=crop", public_id: "seed2/varkala_cottage_1" },
      { url: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop", public_id: "seed2/varkala_cottage_2" },
    ],
    avgRating: 4.79, reviewCount: 156,
  },
  // WEST BENGAL
  {
    title: "Heritage Mansion, Kolkata",
    description: "A beautifully restored 19th century zamindar mansion in the heart of North Kolkata's heritage district. Belgian glass windows, Italian marble floors, and Corinthian columns create a magnificent backdrop. Walking distance to Marble Palace, Kumartuli and the Ganges ghats.",
    propertyType: "house",
    pricePerNight: 4800,
    cleaningFee: 700,
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "TV", "Workspace", "Free parking"],
    location: { city: "Kolkata", state: "West Bengal", country: "India", address: "Sovabazar, North Kolkata", coordinates: { lat: 22.5726, lng: 88.3639 } },
    images: [
      { url: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200&h=800&fit=crop", public_id: "seed2/kolkata_mansion_1" },
      { url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&h=800&fit=crop", public_id: "seed2/kolkata_mansion_2" },
    ],
    avgRating: 4.68, reviewCount: 89,
  },
  // ASSAM
  {
    title: "Tea Estate Bungalow, Jorhat",
    description: "A classic British-era planter's bungalow set in the heart of Assam's famous tea gardens. Surrounded by endless rows of emerald tea bushes, with a tiger reserve nearby. Experience the morning tea plucking ritual, visit the factory, and enjoy high tea on the verandah.",
    propertyType: "house",
    pricePerNight: 5500,
    cleaningFee: 900,
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ["WiFi", "Air conditioning", "Breakfast", "Free parking", "TV", "Pet friendly"],
    location: { city: "Jorhat", state: "Assam", country: "India", address: "Tocklai Tea Estate, Jorhat", coordinates: { lat: 26.7509, lng: 94.2037 } },
    images: [
      { url: "https://images.unsplash.com/photo-1468824357306-a439d58ccb1c?w=1200&h=800&fit=crop", public_id: "seed2/jorhat_estate_1" },
      { url: "https://images.unsplash.com/photo-1444464666168-49d633b86797?w=1200&h=800&fit=crop", public_id: "seed2/jorhat_estate_2" },
    ],
    avgRating: 4.84, reviewCount: 67,
  },
  // MEGHALAYA
  {
    title: "Cloud Forest Cottage, Shillong",
    description: "A cozy pine-wood cottage in the Scotland of the East, perched above the clouds with views of the Khasi Hills. Nearby attractions include the famous living root bridges, Cherrapunji waterfalls, and Dawki river. Experience the unique Khasi culture and cuisine.",
    propertyType: "cottage",
    pricePerNight: 3200,
    cleaningFee: 500,
    maxGuests: 4,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    amenities: ["WiFi", "Heating", "Kitchen", "Indoor fireplace", "Free parking", "TV"],
    location: { city: "Shillong", state: "Meghalaya", country: "India", address: "Laitumkhrah, Shillong", coordinates: { lat: 25.5788, lng: 91.8933 } },
    images: [
      { url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&h=800&fit=crop", public_id: "seed2/shillong_cottage_1" },
      { url: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&h=800&fit=crop", public_id: "seed2/shillong_cottage_2" },
    ],
    avgRating: 4.76, reviewCount: 112,
  },
  // SIKKIM
  {
    title: "Himalayan Monastery Retreat, Gangtok",
    description: "A peaceful retreat center next to an ancient Buddhist monastery with jaw-dropping views of Mount Kanchenjunga. Wake up to chanting monks, practice morning meditation, and witness spectacular Himalayan sunrises. Organic meals served in the traditional Sikkimese style.",
    propertyType: "resort",
    pricePerNight: 6800,
    cleaningFee: 1000,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Heating", "Breakfast", "Free parking", "TV", "Gym"],
    location: { city: "Gangtok", state: "Sikkim", country: "India", address: "Near Rumtek Monastery, Gangtok", coordinates: { lat: 27.3389, lng: 88.6065 } },
    images: [
      { url: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop", public_id: "seed2/gangtok_retreat_1" },
      { url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&h=800&fit=crop", public_id: "seed2/gangtok_retreat_2" },
    ],
    avgRating: 4.92, reviewCount: 78,
  },
  // GUJARAT
  {
    title: "Rann Utsav Tent City, Kutch",
    description: "Luxury air-conditioned Swiss tents at the edge of the Great Rann of Kutch — the world's largest salt desert. Witness the magical white desert under full moonlight and experience the vibrant Kutchi folk culture. Hot air balloon rides, folk performances, and craft village tours included.",
    propertyType: "hotel",
    pricePerNight: 9500,
    cleaningFee: 1500,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Air conditioning", "Breakfast", "BBQ grill", "Free parking", "TV"],
    location: { city: "Bhuj", state: "Gujarat", country: "India", address: "Dhordo, Rann of Kutch", coordinates: { lat: 23.6345, lng: 69.6669 } },
    images: [
      { url: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&h=800&fit=crop", public_id: "seed2/kutch_tent_1" },
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop", public_id: "seed2/kutch_tent_2" },
    ],
    avgRating: 4.90, reviewCount: 134,
  },
  // MAHARASHTRA
  {
    title: "Cliffside Resort, Mahabaleshwar",
    description: "Stunning resort perched on the Western Ghats escarpment with valley views stretching 50km. Private infinity pool seemingly merging with the horizon, strawberry farms on property, and private hiking trails through dense forests. Perfect for monsoon getaways.",
    propertyType: "resort",
    pricePerNight: 10500,
    cleaningFee: 1800,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Air conditioning", "Pool", "Breakfast", "Gym", "Free parking", "TV", "Spa"],
    location: { city: "Mahabaleshwar", state: "Maharashtra", country: "India", address: "Panorama Point, Mahabaleshwar", coordinates: { lat: 17.9307, lng: 73.6477 } },
    images: [
      { url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&h=800&fit=crop", public_id: "seed2/mahabaleshwar_resort_1" },
      { url: "https://images.unsplash.com/photo-1540541338537-71f7ce3e82e7?w=1200&h=800&fit=crop", public_id: "seed2/mahabaleshwar_resort_2" },
    ],
    avgRating: 4.88, reviewCount: 198,
  },
  {
    title: "Designer Loft, Bandra Mumbai",
    description: "Sleek industrial-chic loft in Bandra's most sought-after neighbourhood. Exposed brick walls, floor-to-ceiling windows, and custom Italian furniture. Rooftop terrace with Mumbai skyline views, Netflix, high-speed WiFi, and walking distance to the best restaurants in the city.",
    propertyType: "loft",
    pricePerNight: 6200,
    cleaningFee: 1000,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Washer", "TV", "Workspace", "Gym"],
    location: { city: "Mumbai", state: "Maharashtra", country: "India", address: "Carter Road, Bandra West", coordinates: { lat: 19.0612, lng: 72.8258 } },
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop", public_id: "seed2/mumbai_loft_1" },
      { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop", public_id: "seed2/mumbai_loft_2" },
    ],
    avgRating: 4.82, reviewCount: 267,
  },
  // MADHYA PRADESH
  {
    title: "Jungle Lodge, Kanha",
    description: "Exclusive teak forest lodge on the buffer zone of Kanha Tiger Reserve — the inspiration for Rudyard Kipling's Jungle Book. Expert naturalists guide dawn and dusk safaris in open jeeps. Encounter tigers, leopards, barasingha deer and hundreds of bird species in their natural habitat.",
    propertyType: "resort",
    pricePerNight: 18000,
    cleaningFee: 2500,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Air conditioning", "Breakfast", "Free parking", "TV", "Pool"],
    location: { city: "Kanha", state: "Madhya Pradesh", country: "India", address: "Kanha Tiger Reserve Buffer Zone", coordinates: { lat: 22.2688, lng: 80.6148 } },
    images: [
      { url: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=1200&h=800&fit=crop", public_id: "seed2/kanha_lodge_1" },
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=800&fit=crop", public_id: "seed2/kanha_lodge_2" },
    ],
    avgRating: 4.97, reviewCount: 43,
  },
  // PUNJAB
  {
    title: "Heritage Farmhouse, Amritsar",
    description: "A sprawling Punjabi farmhouse with mustard fields and a private swimming pool, just 15 minutes from the Golden Temple. Wake up to authentic Punjabi breakfast — sarson ka saag, makki di roti and lassi. Tractor rides through fields, evening bonfire and bhangra performances arranged.",
    propertyType: "house",
    pricePerNight: 5500,
    cleaningFee: 900,
    maxGuests: 12,
    bedrooms: 5,
    beds: 7,
    bathrooms: 3,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Pool", "Breakfast", "Free parking", "TV", "BBQ grill"],
    location: { city: "Amritsar", state: "Punjab", country: "India", address: "GT Road, Near Golden Temple", coordinates: { lat: 31.6340, lng: 74.8723 } },
    images: [
      { url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&h=800&fit=crop", public_id: "seed2/amritsar_farmhouse_1" },
      { url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=1200&h=800&fit=crop", public_id: "seed2/amritsar_farmhouse_2" },
    ],
    avgRating: 4.87, reviewCount: 189,
  },
  // TELANGANA
  {
    title: "Lakeside Villa, Hyderabad",
    description: "Contemporary villa overlooking Hussain Sagar Lake with stunning views of the Buddha statue. Featuring a private infinity pool, home theatre, and a dedicated biryani chef. Minutes from HITEC City, Golconda Fort and the famous Charminar bazaars.",
    propertyType: "villa",
    pricePerNight: 12000,
    cleaningFee: 2000,
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Pool", "Waterfront", "Gym", "Free parking", "TV"],
    location: { city: "Hyderabad", state: "Telangana", country: "India", address: "Tank Bund Road, Hussain Sagar", coordinates: { lat: 17.4239, lng: 78.4738 } },
    images: [
      { url: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&h=800&fit=crop", public_id: "seed2/hyderabad_villa_1" },
      { url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&h=800&fit=crop", public_id: "seed2/hyderabad_villa_2" },
    ],
    avgRating: 4.85, reviewCount: 156,
  },
  // ODISHA
  {
    title: "Beach Bungalow, Puri",
    description: "Traditional Odia bungalow with a private beach and views of the Bay of Bengal. Just steps from the famous Puri Beach and 2km from the Jagannath Temple. Fresh catch seafood prepared daily, traditional Odia pitha breakfast, and guided temple tours arranged.",
    propertyType: "house",
    pricePerNight: 4500,
    cleaningFee: 700,
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Beachfront", "Breakfast", "Free parking", "TV"],
    location: { city: "Puri", state: "Odisha", country: "India", address: "Marine Drive, Puri Beach", coordinates: { lat: 19.7979, lng: 85.8245 } },
    images: [
      { url: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop", public_id: "seed2/puri_bungalow_1" },
      { url: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1200&h=800&fit=crop", public_id: "seed2/puri_bungalow_2" },
    ],
    avgRating: 4.73, reviewCount: 134,
  },
  // JHARKHAND
  {
    title: "Eco Lodge, Betla National Park",
    description: "Rustic yet comfortable eco lodge inside the Betla (Palamau) National Park — one of India's original Project Tiger reserves. Listen to elephants at night, spot tigers and leopards on morning drives, and enjoy bonfires under a canopy of stars. Basic but magical.",
    propertyType: "cabin",
    pricePerNight: 3500,
    cleaningFee: 500,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Breakfast", "Free parking", "BBQ grill"],
    location: { city: "Betla", state: "Jharkhand", country: "India", address: "Betla National Park, Palamau", coordinates: { lat: 23.9244, lng: 84.0643 } },
    images: [
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=800&fit=crop", public_id: "seed2/betla_ecolodge_1" },
      { url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&h=800&fit=crop", public_id: "seed2/betla_ecolodge_2" },
    ],
    avgRating: 4.65, reviewCount: 45,
  },
  // BIHAR
  {
    title: "Spiritual Retreat, Bodh Gaya",
    description: "A serene meditation center and guesthouse in the sacred town where the Buddha attained enlightenment. Simple yet elegant rooms, vegetarian meals, daily meditation sessions, and guided tours to the Mahabodhi Temple complex — a UNESCO World Heritage Site.",
    propertyType: "hotel",
    pricePerNight: 2500,
    cleaningFee: 300,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Breakfast", "Free parking", "TV"],
    location: { city: "Bodh Gaya", state: "Bihar", country: "India", address: "Near Mahabodhi Temple, Bodh Gaya", coordinates: { lat: 24.6961, lng: 84.9912 } },
    images: [
      { url: "https://images.unsplash.com/photo-1549144511-f099e773c147?w=1200&h=800&fit=crop", public_id: "seed2/bodhgaya_retreat_1" },
      { url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop", public_id: "seed2/bodhgaya_retreat_2" },
    ],
    avgRating: 4.71, reviewCount: 98,
  },
  // CHHATTISGARH
  {
    title: "Waterfall Retreat, Chitrakote",
    description: "A jungle resort beside the magnificent Chitrakote Falls — India's widest waterfall, often called the Niagara of India. Wake up to the roar of the falls, spot tribal crafts at nearby haats, and take boat rides to the base of the cascade. A hidden gem of central India.",
    propertyType: "resort",
    pricePerNight: 4800,
    cleaningFee: 700,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Air conditioning", "Breakfast", "Waterfront", "Free parking", "TV"],
    location: { city: "Jagdalpur", state: "Chhattisgarh", country: "India", address: "Chitrakote Falls, Bastar", coordinates: { lat: 19.1097, lng: 81.8593 } },
    images: [
      { url: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1200&h=800&fit=crop", public_id: "seed2/chitrakote_resort_1" },
      { url: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&h=800&fit=crop", public_id: "seed2/chitrakote_resort_2" },
    ],
    avgRating: 4.78, reviewCount: 62,
  },
  // ANDHRA PRADESH
  {
    title: "Beach House, Vizag",
    description: "A modern 3-bedroom beach house on RK Beach, Visakhapatnam. Private deck facing the Bay of Bengal, BBQ setup, and a fully equipped kitchen. Close to the famous Submarine Museum, Kailasagiri hill park, and the vibrant Vizag food street.",
    propertyType: "house",
    pricePerNight: 6800,
    cleaningFee: 1100,
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Beachfront", "BBQ grill", "Free parking", "TV"],
    location: { city: "Visakhapatnam", state: "Andhra Pradesh", country: "India", address: "RK Beach Road, Vizag", coordinates: { lat: 17.7129, lng: 83.3236 } },
    images: [
      { url: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&h=800&fit=crop", public_id: "seed2/vizag_house_1" },
      { url: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop", public_id: "seed2/vizag_house_2" },
    ],
    avgRating: 4.80, reviewCount: 167,
  },
  // JAMMU & KASHMIR
  {
    title: "Luxury Shikara Houseboat, Dal Lake",
    description: "A beautifully carved traditional shikara houseboat on the famous Dal Lake in Srinagar. Hand-painted papier-mâché ceilings, walnut wood carvings, Persian carpets, and a private sun deck. Enjoy sunrise shikara rides, floating vegetable markets, and Wazwan cuisine.",
    propertyType: "house",
    pricePerNight: 7500,
    cleaningFee: 1200,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Heating", "Breakfast", "Waterfront", "TV"],
    location: { city: "Srinagar", state: "Jammu and Kashmir", country: "India", address: "Dal Lake, Srinagar", coordinates: { lat: 34.0837, lng: 74.7973 } },
    images: [
      { url: "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?w=1200&h=800&fit=crop", public_id: "seed2/srinagar_houseboat_1" },
      { url: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&h=800&fit=crop", public_id: "seed2/srinagar_houseboat_2" },
    ],
    avgRating: 4.96, reviewCount: 289,
  },
  {
    title: "Mountain Chalet, Gulmarg",
    description: "A ski-in ski-out chalet in Gulmarg — Asia's highest and largest cable car destination. In winter, world-class powder skiing; in summer, wildflower meadows and pony rides. Cozy fireplace, panoramic snow views, and proximity to the famous Gulmarg Gondola.",
    propertyType: "cabin",
    pricePerNight: 9800,
    cleaningFee: 1500,
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ["WiFi", "Heating", "Kitchen", "Indoor fireplace", "Free parking", "TV", "Breakfast"],
    location: { city: "Gulmarg", state: "Jammu and Kashmir", country: "India", address: "Near Gondola Station, Gulmarg", coordinates: { lat: 34.0484, lng: 74.3805 } },
    images: [
      { url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&h=800&fit=crop", public_id: "seed2/gulmarg_chalet_1" },
      { url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop", public_id: "seed2/gulmarg_chalet_2" },
    ],
    avgRating: 4.93, reviewCount: 112,
  },
  // LADAKH
  {
    title: "Mud House Homestay, Leh",
    description: "Authentic Ladakhi mud-brick homestay with traditional whitewashed rooms, prayer flags, and breathtaking views of the Stok Kangri range. Experience local Ladakhi culture, thukpa noodles, butter tea, and guided treks to ancient monasteries at 3500m altitude.",
    propertyType: "house",
    pricePerNight: 3200,
    cleaningFee: 500,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Heating", "Breakfast", "Free parking"],
    location: { city: "Leh", state: "Ladakh", country: "India", address: "Old Leh Town, Near Shanti Stupa", coordinates: { lat: 34.1526, lng: 77.5771 } },
    images: [
      { url: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop", public_id: "seed2/leh_homestay_1" },
      { url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&h=800&fit=crop", public_id: "seed2/leh_homestay_2" },
    ],
    avgRating: 4.88, reviewCount: 203,
  },
  // HARYANA
  {
    title: "Luxury Farm Stay, Gurugram",
    description: "A peaceful organic farm retreat just 45 minutes from Connaught Place. Sprawling 10-acre property with organic vegetable gardens, vintage tractor rides, pottery classes, and traditional Haryanvi thali meals. Perfect weekend escape from Delhi-NCR hustle.",
    propertyType: "house",
    pricePerNight: 5800,
    cleaningFee: 900,
    maxGuests: 10,
    bedrooms: 4,
    beds: 6,
    bathrooms: 3,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Pool", "Breakfast", "Free parking", "TV", "BBQ grill", "Pet friendly"],
    location: { city: "Gurugram", state: "Haryana", country: "India", address: "Sohna Road, Near Gurugram", coordinates: { lat: 28.3908, lng: 77.0303 } },
    images: [
      { url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&h=800&fit=crop", public_id: "seed2/gurugram_farmstay_1" },
      { url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=1200&h=800&fit=crop", public_id: "seed2/gurugram_farmstay_2" },
    ],
    avgRating: 4.82, reviewCount: 145,
  },
  // UTTAR PRADESH
  {
    title: "Heritage Guest House, Varanasi",
    description: "A stunning 200-year-old haveli on the ghats of the holy Ganges in Varanasi. Watch the magnificent Ganga Aarti ceremony from your private balcony every evening. Early morning boat rides, guided temple trails, and authentic Banarasi cuisine complete this unforgettable spiritual experience.",
    propertyType: "house",
    pricePerNight: 4200,
    cleaningFee: 600,
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ["WiFi", "Air conditioning", "Breakfast", "Waterfront", "TV"],
    location: { city: "Varanasi", state: "Uttar Pradesh", country: "India", address: "Dashashwamedh Ghat, Varanasi", coordinates: { lat: 25.3176, lng: 83.0130 } },
    images: [
      { url: "https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&h=800&fit=crop", public_id: "seed2/varanasi_haveli_1" },
      { url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1200&h=800&fit=crop", public_id: "seed2/varanasi_haveli_2" },
    ],
    avgRating: 4.89, reviewCount: 312,
  },
  // TRIPURA
  {
    title: "Royal Palace Hotel, Agartala",
    description: "Stay in a wing of the magnificent Ujjayanta Palace, former seat of the royal House of Tripura. Ornate halls, royal portraits, and manicured Mughal gardens create a fairy-tale setting. The palace museum, traditional Tripuri crafts market, and local bamboo cuisine await.",
    propertyType: "hotel",
    pricePerNight: 4500,
    cleaningFee: 700,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Air conditioning", "Breakfast", "Free parking", "TV", "Gym"],
    location: { city: "Agartala", state: "Tripura", country: "India", address: "Palace Compound, Agartala", coordinates: { lat: 23.8315, lng: 91.2868 } },
    images: [
      { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop", public_id: "seed2/agartala_palace_1" },
      { url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&h=800&fit=crop", public_id: "seed2/agartala_palace_2" },
    ],
    avgRating: 4.69, reviewCount: 56,
  },
  // ARUNACHAL PRADESH
  {
    title: "Monastery Guesthouse, Tawang",
    description: "A cozy guesthouse adjacent to the legendary Tawang Monastery — the largest Buddhist monastery in India and second largest in the world. Stunning views of snow-capped peaks, prayer wheel walks at dawn, and the unique Monpa tribal culture and cuisine.",
    propertyType: "hotel",
    pricePerNight: 3800,
    cleaningFee: 500,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Heating", "Breakfast", "Free parking", "TV"],
    location: { city: "Tawang", state: "Arunachal Pradesh", country: "India", address: "Near Tawang Monastery", coordinates: { lat: 27.5861, lng: 91.8594 } },
    images: [
      { url: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop", public_id: "seed2/tawang_guesthouse_1" },
      { url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&h=800&fit=crop", public_id: "seed2/tawang_guesthouse_2" },
    ],
    avgRating: 4.83, reviewCount: 71,
  },
  // MANIPUR
  {
    title: "Lake View Bungalow, Imphal",
    description: "A serene bungalow overlooking the famous Loktak Lake — the largest freshwater lake in Northeast India, home to the unique floating phumdis. Watch the sunrise paint the floating islands golden, spot rare Sangai deer at the nearby reserve, and enjoy authentic Manipuri cuisine.",
    propertyType: "house",
    pricePerNight: 3200,
    cleaningFee: 450,
    maxGuests: 5,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Breakfast", "Free parking", "Waterfront"],
    location: { city: "Imphal", state: "Manipur", country: "India", address: "Loktak Lake View, Moirang", coordinates: { lat: 24.5195, lng: 93.9213 } },
    images: [
      { url: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1200&h=800&fit=crop", public_id: "seed2/imphal_bungalow_1" },
      { url: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&h=800&fit=crop", public_id: "seed2/imphal_bungalow_2" },
    ],
    avgRating: 4.74, reviewCount: 48,
  },
  // NAGALAND
  {
    title: "Tribal Heritage Lodge, Kohima",
    description: "Experience authentic Naga tribal culture in this beautifully crafted wooden lodge near the famous Dzukou Valley. Visit Naga morung villages, witness traditional warrior dances, taste smoked pork and fermented bamboo shoots, and trek through the Valley of Flowers of the Northeast.",
    propertyType: "cabin",
    pricePerNight: 3500,
    cleaningFee: 500,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Heating", "Breakfast", "Free parking", "BBQ grill"],
    location: { city: "Kohima", state: "Nagaland", country: "India", address: "Near Dzukou Valley, Kohima", coordinates: { lat: 25.6699, lng: 94.1097 } },
    images: [
      { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=800&fit=crop", public_id: "seed2/kohima_lodge_1" },
      { url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&h=800&fit=crop", public_id: "seed2/kohima_lodge_2" },
    ],
    avgRating: 4.86, reviewCount: 38,
  },
  // MIZORAM
  {
    title: "Hilltop Cottage, Aizawl",
    description: "A charming cottage perched on Aizawl's famous ridge with panoramic views of green valleys and misty hills. Experience the unique Mizo culture, try bamboo shoot delicacies, and explore the weekly Luangmual market. A peaceful escape in India's least-explored state.",
    propertyType: "cottage",
    pricePerNight: 2800,
    cleaningFee: 400,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Heating", "Kitchen", "Breakfast", "Free parking"],
    location: { city: "Aizawl", state: "Mizoram", country: "India", address: "Durtlang Hills, Aizawl", coordinates: { lat: 23.7271, lng: 92.7176 } },
    images: [
      { url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&h=800&fit=crop", public_id: "seed2/aizawl_cottage_1" },
      { url: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop", public_id: "seed2/aizawl_cottage_2" },
    ],
    avgRating: 4.70, reviewCount: 34,
  },
  // PONDICHERRY
  {
    title: "French Quarter Boutique Villa, Pondicherry",
    description: "A stunning 19th-century French Creole villa in Pondicherry's famous White Town. Pastel-painted walls, bougainvillea-draped courtyard, and a rooftop pool. Walking distance to the Promenade beach, Sri Aurobindo Ashram, and the finest French bakeries in India.",
    propertyType: "villa",
    pricePerNight: 8500,
    cleaningFee: 1400,
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Pool", "Breakfast", "TV", "Workspace"],
    location: { city: "Pondicherry", state: "Puducherry", country: "India", address: "White Town, Pondicherry", coordinates: { lat: 11.9340, lng: 79.8370 } },
    images: [
      { url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=1200&h=800&fit=crop", public_id: "seed2/pondy_villa_1" },
      { url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&h=800&fit=crop", public_id: "seed2/pondy_villa_2" },
    ],
    avgRating: 4.95, reviewCount: 276,
  },
  // GOA EXTRA
  {
    title: "Portuguese Mansion, South Goa",
    description: "A magnificent 400-year-old Portuguese mansion in the heart of Old Goa. Original azulejo tile work, four-poster beds, and a tropical garden with century-old mango trees. Guests enjoy complimentary bicycle hire, sunset river cruises, and traditional Goan fish curry cooking classes.",
    propertyType: "villa",
    pricePerNight: 15000,
    cleaningFee: 2500,
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Pool", "Breakfast", "Free parking", "TV", "Workspace"],
    location: { city: "Goa", state: "Goa", country: "India", address: "Old Goa, Near Se Cathedral", coordinates: { lat: 15.5009, lng: 73.9119 } },
    images: [
      { url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&h=800&fit=crop", public_id: "seed2/goa_mansion_1" },
      { url: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&h=800&fit=crop", public_id: "seed2/goa_mansion_2" },
    ],
    avgRating: 4.98, reviewCount: 167,
  },
  // DELHI EXTRA
  {
    title: "Luxury Penthouse, Lutyens Delhi",
    description: "An ultra-premium penthouse in the heart of Lutyens Delhi with a private rooftop pool and 360-degree views of Rashtrapati Bhavan and India Gate. Custom Italian furniture, smart home systems, and a dedicated concierge service. The pinnacle of luxury living in the capital.",
    propertyType: "apartment",
    pricePerNight: 35000,
    cleaningFee: 5000,
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 3,
    amenities: ["WiFi", "Air conditioning", "Kitchen", "Pool", "Gym", "Washer", "TV", "Workspace", "Free parking", "Hot tub"],
    location: { city: "Delhi", state: "Delhi", country: "India", address: "Aurangzeb Road, Lutyens Delhi", coordinates: { lat: 28.6003, lng: 77.2091 } },
    images: [
      { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop", public_id: "seed2/delhi_penthouse_1" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop", public_id: "seed2/delhi_penthouse_2" },
    ],
    avgRating: 4.96, reviewCount: 89,
  },
];

async function seedExtra() {
  try {
    console.log("🔌 Connecting to MongoDB...");
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ MongoDB connected!");

    let hostUser = await User.findOne({ email: "host@stayease.com" });
    if (!hostUser) {
      hostUser = await User.create({
        name: "StayEase Host",
        email: "host@stayease.com",
        password: "Host@123456",
        role: "host",
        isVerified: true,
        bio: "Official StayEase sample host account",
      });
      console.log("✅ Host user created: host@stayease.com / Host@123456");
    }

    // Remove old seed2 listings
    await Listing.deleteMany({ "images.public_id": /^seed2\// });
    console.log("🗑️  Old extra listings removed");

    const listingsWithHost = EXTRA_LISTINGS.map(l => ({ ...l, host: hostUser._id }));
    const created = await Listing.insertMany(listingsWithHost);
    console.log(`✅ ${created.length} new listings added!`);

    const total = await Listing.countDocuments();
    console.log(`📊 Total listings in DB: ${total}`);
    console.log("\n🎉 Done! Open → http://localhost:5173/listings");

    await mongoose.disconnect();
    process.exit(0);
  } catch (err) {
    console.error("❌ Seed failed:", err.message);
    process.exit(1);
  }
}

seedExtra();
